# Set to true to add assignees to pull requests
addAssignees: author

# Set to true to add reviewers to pull requests
addReviewers: true
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
# Set to true to add reviewers from different groups to pull requests
useReviewGroups: true
# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewGroups:
  groupA:
    - ManjiDM
  groupB:
    - AtomDM


runOnDraft: true
# Set to true to add assignees from different groups to pull requests
