# Set to true to add assignees to pull requests
addAssignees: author
useAssigneeGroups: false
# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1

# Set to true to add reviewers to pull requests
addReviewers: true
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
# Set to true to add reviewers from different groups to pull requests
useReviewGroups: true
# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewGroups:
  groupA:
    - ManjiDM
    - reviewerB
    - reviewerC
  groupB:
    - AtomDM
    - reviewerE
    - reviewerF


runOnDraft: true
# Set to true to add assignees from different groups to pull requests
