name: keyword-releaser
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ManjiDM/CustomAction@main
        with: 
          GITHUB_TOKEN: ${{ secrets.PAT }}
          args: 'FIXED'
          
