name: Publish Coverage Report
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build project
        run: |
          echo "Building the project..."
          mvn clean install
      - name: Publish Coverage Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Publishing coverage report..."
          mkdir -p coverage-report
          cp -r target/jacoco-report/* coverage-report/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b gh-pages
          mv coverage-report/* .
          git add .
          git commit -m "Publish coverage report"
          git push origin gh-pages --force
