name: Challenge 02
on: push
env:
    ARTIFACT_NAME: "artifact_name"
jobs:
    check-out:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.4
              with: 
                repository: ${{github.repository}}
    upload-artifact:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: "${{ env.ARTIFACT_NAME }}"
                  path: "artifact"
                  if-no-files-found: warn
