name: Challenge 03
on: push

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4.1.4
      - name: setup python
        uses: actions/setup-python@v5.1.0
      - name: run script  
        run: python hello.py
  artifact:
    runs-on: ubuntu-latest 
    needs: check-out
    steps:       
      - name: checkout 
        uses: actions/checkout@v4.1.4  
      - name: create artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ./.github/workflows 
          if-no-files-found: error
          
