name: first workflow
on: push

jobs:
    job1:
        name: 1stJob
        runs-on: ubuntu-latest
        steps:
            - run: env | sort
    job2:
        name: 2ndJob
        runs-on: windows-latest
        steps:
            - run: "Get-ChildItem Env: | Sort-Object Name"
    job3:
        name: 3rdJob
        needs: [ job1, job2]
        runs-on: ubuntu-latest
        steps:
            - run: "echo finished"
