name: first workflow
on: push

jobs:
    job1:
        name: 1stJob
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              run: env | sort

    job2:
        name: 2ndJob
        runs-on: windows-latest
        steps:
            - name: Step one
              run: "Get-ChildItem Env: | Sort-Object Name"
    job2:
    name: 3rdJob
    needs: [ job1, job2]
    runs-on: ubuntu-latest
    steps:
        - name: Step two
            run: "echo finished"
